#!/usr/bin/env node

'use strict';

var argv = require('optimist').argv,
	fs = require('fs'),
	mkdirp = require('mkdirp'),
	EXAMPLES = __dirname+'/examples/';

mkdirp(__dirname+'/dist', function(err){});

if ((argv.list || !argv._.length) && !argv.file) return list(1);

if (argv.file) {
	moveFile(argv.file);
};

function list (talk) {
	var fd = fs.statSync(EXAMPLES);

	if (!fd || !fd.isDirectory()) {
		return talk ? console.log('Cannot find examples directory') : null;
	};

	var files = fs.readdirSync(EXAMPLES).map(function(fd){
		return fd;
	});

	if (talk) {
		files.unshift('\nAvailable example grunt files:\n');
		files.push('\nUsage: $ ./changegruntfile --file=uglify.js\n');
		console.log(files.join('\n'));
	};

	return files;
};

function moveFile (file) {
	if (!~file.indexOf('.js')) file += '.js';

	var fdLoc = EXAMPLES+file,
		fd = null;

	try {
		fd = fs.statSync(fdLoc);
	} catch (e) {
		console.log('Cannot find example file: %s', fdLoc);
		return list(1);
	};

	var src = fs.createReadStream(fdLoc),
		dest = fs.createWriteStream(__dirname+'/Gruntfile.js');

	src.pipe(dest);
	src.pipe(process.stdout);

	console.log('\nNow using example %s Gruntfile\n', file);
};
